### ISSUE TITLE
[UI-FIX] CSC LOGO in iOS app gallery

### ISSUE THREAD

**Issue by t-jacobi** [asgiom/cr8-brm-mobile-issues#128]
**Section or interface element**
If you double tab the home button on iOS you will get all open apps. 
The icon for the CR8 wallet is the casinocoin logo. 

**Reason**
IDK

**Description**
Should be the CR8 logo. 

**Screenshots**
![IMG_4372](https://user-images.githubusercontent.com/46750418/94016775-dd783180-fdae-11ea-8023-7cc5c001e900.png)

** System **
iPhone 6s, iOS 13.6.1

**Comment by t3nshi** [comment]
Look @ajochems, this guy came back... I am referring to the little icon of course...

**Comment by georgemac70cr8** [comment]
fixed for version 0.5.7. let's just wait until 0.5.8. and we can confirm it has been fixed on that version. then we can close.

**Comment by t-jacobi** [comment]
@t3nshi @ajochems downloaded 0.5.8 on testflight and the issue still exists. I've reinstalled the app with same issue. iOS 13.6.1, iPhone 6s

**Comment by t3nshi** [comment]
Well some versions ago was fixed for all except for testflight... so can you please try to validate if you have the issue with no testflight?, so we can make sure it's some testflight quirk and not the app?

**Comment by ibanezvaio** [comment]
![image1 (1)](https://user-images.githubusercontent.com/2853264/94927766-a1358700-04ba-11eb-97a0-9d25e6c1bee6.png)

 Looks ok to me - this is a Testflight version

**Comment by t3nshi** [comment]
but the key point here... and that's why I said it was fixed everywhere but in testflight... did you had the broken version before? or only this one... it seems that once you install an app through testflight some assets (like this icon) will be cached and persist across versions... but if this was your first testflight version installed you won't see the issue. Please consider this in the light of this information and let me know your thoughts about it.

**Comment by t-jacobi** [comment]
It seams to be a caching issue, after some days with 0.5.9 from testlfight it shows now the correct icon! i will close the issue.
