### ISSUE TITLE
[BUG] Unable to launch app - Biometric sign on

### ISSUE THREAD

**Issue by moatazkhalifa** [asgiom/cr8-brm-mobile-issues#26]
**Describe the bug**
On launch, the login/recover wallet buttons are no longer functional. I get a message for Biometric sign on that does nothing, then I get a screen for wallet recovery, which also does nothing (If I tap any of the buttons or anywhere it does nothing).

Then, when I use my fingerprint, it loads the app with no issues.

Closed, re-opened the app, and it asks for fingerprint every time. Shouldn't it ask for PIN instead??

**Screenshots**
![Screenshot_20200819-201031_CR8 Wallet](https://user-images.githubusercontent.com/60157931/90674093-f2662000-e258-11ea-980b-95fd085258c5.jpg)
![Screenshot_20200819-201205_CR8 Wallet](https://user-images.githubusercontent.com/60157931/90674096-f4c87a00-e258-11ea-8897-7c02b0d58c10.jpg)
![Screenshot_20200819-201255_CR8 Wallet](https://user-images.githubusercontent.com/60157931/90674107-f72ad400-e258-11ea-90da-70f2eca2cd59.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S9+
 - OS: Android 10
 - App Version 46

**Comment by moatazkhalifa** [comment]
Additionally, when login button is tapped, the 'Login' button is all in orange like the 1st screenshot

**Comment by moatazkhalifa** [comment]
Also, I noticed it says 'CasinCoin' wallet on the 2nd screenshot

**Comment by t3nshi** [comment]
I am not sure, but this sounds like the intended behaviour. When you enable biometrics you replace the PIN with the fingerprint. Anytime the popup with the fingerprint appears is requesting your "PIN" by using your fingerprint. I was following the steps you provided and could reproduce everything you said, except that this way it supposed to work. When you tap on login, or on any action that usually triggers the PIN, it nows shows a grey pop up with a fingerprint, and you should use your fingerprint scanner to move on. if you tap anything won't work, and if you cancel it will show the alert saying that you could not log or authenticate because you dismissed the fingerprint request...  if you still are experiencing any problem or if I'm misunderstanding let me know.

**Comment by moatazkhalifa** [comment]
The app never asked me for Biometrics during the setup, it only asked to set up a PIN.

If this behavior is intentional then it shouldn't ask for PIN and only ask for Fingerprint during setup. And all text that says PIN should be replaced with Fingerprint.

Very confusing
