### ISSUE TITLE
[BUG]QR Code not displayed correct on smaller devices

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#44]
**Section or interface element**
QR code needs to be displayed correct

**Reason**
Otherwise it wont work

**Description**
QR code should be fully displayed even on smaller devices.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/91358945-fd3e2900-e7f3-11ea-952a-4527dcf963dd.png)

**Comment by t3nshi** [comment]
this is clearly a bug, since it is not causing just discomfort but disabling functionality. Can you provide details in which phones this is happening. I tried in 4 diferent devices, the smallest screen available around here, and no success. But I can't reproduce it. thank you for your additional information

**Comment by danielwwf** [comment]
Moto G7 Play

**Comment by danielwwf** [comment]
https://github.com/asgiom/cr8-brm-mobile-issues/issues/45

**Comment by Mattch33** [comment]
Fixed on S9 Saumsung

**Comment by danielwwf** [comment]
fixed
