### ISSUE TITLE
[UI-FIX]Terms of Service text changes - remove line break from one of headings

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#51]
**Section or interface element**

terms of service on initial installation.
There were a couple of small grammar errors. Rather than change the whole doc (in case we mess up the layout), I have just shown the tracked changes in 2 screenshots - so please just make these tiny changes manually thanks.

<img width="504" alt="Screenshot 2020-09-01 at 11 33 00" src="https://user-images.githubusercontent.com/69824025/91833409-f75aa480-ec46-11ea-9970-7a2cb4b212a6.png">
<img width="495" alt="Screenshot 2020-09-01 at 11 33 08" src="https://user-images.githubusercontent.com/69824025/91833425-fb86c200-ec46-11ea-9b17-358c4ee7d2ed.png">

**Comment by t3nshi** [comment]
Sure will do.

**Comment by georgemac70cr8** [comment]
I have just added 2 new paragrpahs to the liabilty section. I have not included the whole doc just the approproate section - and highlighted in yellow so that the dev team can tell which is the additional text. Please add the text to the ToS but not with yellow highlight!

doc attached for easy copy and paste (no yellow please)

[Full_TermsofService_disclaimer.docx](https://github.com/asgiom/cr8-brm-mobile-issues/files/5174492/Full_TermsofService_disclaimer.docx)

![image](https://user-images.githubusercontent.com/69824025/92234030-9c78b580-eeb1-11ea-8c72-538b3511f8c3.png)

**Comment by t3nshi** [comment]
I don't like to be annoying, but you will help me hugely if next time you paste the text in here, since I will be able to take it right away just like we did last time on another issue... if you upload a doc is a lot of more cumbersome for me, since I almost never use word processors and have to do a long roundabout. Of course, for this one, I already dealt with the overhead... If it is simple for you that way I appreciate it, if it is not, nevermind!

**Comment by georgemac70cr8** [comment]
Remove line break here in ToS - attached screenshot

Just put the whole sentence on the same line

![Screenshot_20200907_134428](https://user-images.githubusercontent.com/69824025/92384516-83ba0b00-f110-11ea-96de-537204b90f62.jpg)

**Comment by t3nshi** [comment]
About the new issue... Actually that was a required hack. In smaller screens the title won't fit in one line and with get cropped, this was done a couple of version ago...
Also... about posting the new things here, hijacking the issue...  I appreciate if next time you open a new issue (it's not the same) so we can close and clear the milestones and don't drag them open in a way that are less concise and difficult to keep track or reference by others. For instance, you made this issue a different thing changing the title. So the original issue if it is or was referenced anywhere else will no longer make any sense, and you don't allow me to clear out completed tasks, so this looks and feels like instead of progressing i'm going back.

**Comment by georgemac70cr8** [comment]
so i'll add this as a new issue and you close this exact issue?
