### ISSUE TITLE
[BUG] Timebased wallet lock doesn't work

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#70]
**Describe the bug**
Settings -> Timeout to auto-logout 

No matter what you set, the setting has no effect. Auto logout never happens. I also assume that is what makes glitch.

The way that setting is designed looks very bad, it should look and feel like all other settings.

**To Reproduce**
1. Go to settings
2. Set the setting to 1
3. wait for 1 minute
4. Nothing happens

**Expected behavior**
The setting should work and look like all others. If set, the wallet should obey the setting

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: every device
 - OS: every OS
 - OS Version every
 - App Version ALL

**Additional context**

**Comment by t3nshi** [comment]
I will check to see what is causing the issue.

**Comment by t3nshi** [comment]
at last I sorted this out.

**Comment by danielwwf** [comment]
If it is set to the wallet default of "7" it seems to work. once changed, it doesn't anymore. It is unclear what "7" means, like seconds, minutes, hours etc. If you tap on it and put a different number in, it has no effect and from then the logout doesn't happen anymore. 

The UI of this setting is still bad. I suggest changing it to an on/off slider and once set to "on" you get a little button that says "Set", once tapped you get something that selects you the time (like the DOB slider or whatever is system default for a time.)

**Comment by ibanezvaio** [comment]
@t3nshi I've seen this issue in 0.5.2 also. I set the timeout to 1, waited >1 minute with the both in fore and background and I was still able to continue using the app without logging back in

**Comment by t3nshi** [comment]
After some more checking on different devices I realized that the setting is only getting applied on next start of the app, So you change it and after logging out and logging in again it works, in only one phone works right away... I am looking for a fix so we don't have to restart to apply now and I will be back with some thoughts about the UI.... other thing that we need to point out and validate is that this setting only log out the user when the app is put on background, if the app is in foreground it does nothing... That was the intended behavior since the beginning... but I don't know how are you checking up on this.

**Comment by danielwwf** [comment]
After our conversation yesterday, we should just lock the wallet after 5 minutes of being inactive and work on a fix when shipped.

**Comment by t3nshi** [comment]
It seems that @ajochems found some needed corrections on the logic here, I will update if those corrections fix something here.

**Comment by danielwwf** [comment]
The wallet is now logged after 1 minute of inactivity. Fine for now. will be fixed once shipped.
