### ISSUE TITLE
[UI-FIX]Remove line break here in ToS

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#81]
Remove line break here in ToS - attached screenshot

Please just put the whole sentence on the same line.

There are other headings which are longer than this in the ToS and don't wrap to the next line - so it's possible that it can be done?

screenshot added

![Screenshot_20200907_134428](https://user-images.githubusercontent.com/69824025/92409113-ccd58380-f13f-11ea-9b1c-5f2c8e12140c.jpg)

**Comment by t3nshi** [comment]
I am still looking for a way that works on small screens.

**Comment by georgemac70cr8** [comment]
ok, thanks. It's a minor issue as users generally only see it once... but just seems strange when there's other longer headings that don't wrap.

**Comment by t3nshi** [comment]
The strange thing is that there is only one longer header... that gets truncated on smaller screens, but that one you still understand... But the issue here is that the html here was stripped of styling and before I use a different markup to be able to give the titles some margins, but that markup restrict the titles to one line, and when the width don't fit it gets truncated with just some ellipsis at the end, so I'm looking for something that solves this without to going back to the previous cramped layout.

**Comment by t3nshi** [comment]
Finally found a way to wrap the title automatically after many attempts...

**Comment by danielwwf** [comment]
fixed
